# Generated by Django 4.2.4 on 2023-08-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Post Title')),
                ('postDesc', models.TextField(verbose_name='Post Description')),
                ('postImg', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='')),
                ('postTime', models.DateTimeField(blank=True, null=True, verbose_name='')),
            ],
        ),
    ]
