# Generated by Django 4.2.4 on 2023-08-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Product Title')),
                ('Desc', models.TextField(verbose_name='Product Description')),
                ('Img', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Product Image')),
                ('Price', models.PositiveIntegerField(verbose_name='Price')),
            ],
        ),
    ]
