# Generated by Django 4.2.4 on 2023-08-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='coffee-frontend/src/components/product_img/', verbose_name='Product Image'),
        ),
    ]
