# Generated by Django 4.2.4 on 2023-08-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='coffee-frontend/public/product_img/', verbose_name='Product Image'),
        ),
    ]
